In [5]:
import torch
from torch.distributions.multivariate_normal import MultivariateNormal

In [19]:
# example: let V = 0.5 = b I,  then we need a = 1 - b^2 = 3/4
# mean = Vx = bx, cov = a xx^T
b = 0.5
a = 1 - (b ** 2)
x = torch.randn(2)
cov = a * x.reshape(2, 1) @ x.reshape(1, 2)
mean = b * x

# cov is rank 1, so sampling from cov is equivalent to sampling from its equivalent 1 dimensional gaussian in 2d

In [20]:
mean, cov

(tensor([-0.6391,  0.8912]),
 tensor([[ 1.2255, -1.7088],
         [-1.7088,  2.3828]]))

In [21]:
D, Q = torch.linalg.eigh(cov)
D[0] = 0
D = torch.sqrt(D)
sqrt = Q @ torch.diag(D) @ Q.T

tensor([-5.9605e-08,  3.6082e+00])

In [16]:
z = MultivariateNormal(torch.zeros(2), torch.eye(2))
zs = z.sample(torch.Size([500]))
xs = zs + 

torch.Size([500, 2])

In [8]:
num_samples = 500
normal_dist = MultivariateNormal(torch.zeros(2), torch.sqrt(cov))
from_normal = normal_dist.sample((num_samples,))
from_normal.shape


ValueError: Expected parameter covariance_matrix (Tensor of shape (2, 2)) of distribution MultivariateNormal(loc: torch.Size([2]), covariance_matrix: torch.Size([2, 2])) to satisfy the constraint PositiveDefinite(), but found invalid values:
tensor([[ 0.0542, -0.4268],
        [-0.4268,  3.3593]])